### ISSUE TITLE
[psqldef] Setting the default time will result in a syntax error

### ISSUE THREAD

**Issue by shiroemons** [sqldef/sqldef#387]
## Platform

* OS: macOS
* RDBMS: PostgreSQL
* Version: v0.15.22

## --export output

```shell
2023/04/03 16:35:11 found syntax error when parsing DDL "CREATE TABLE "public"."users" (
    "id" bigserial NOT NULL,
    "name" text NOT NULL,
    "hoge_time" time NOT NULL DEFAULT '23:59:59'::time without time zone,
    PRIMARY KEY ("id")
)": syntax error at position 150 near 'without'
```

## Input SQL

```sql
create table users (
  id        bigserial not null primary key,
  name      text      not null,
  hoge_time time      not null default '23:59:59'::time
)
```

## Current output

- When first executed
    ```shell
    -- Apply --
    create table users (
    id        bigserial not null primary key,
    name      text      not null,
    hoge_time time      not null default '23:59:59'::time
    );
    ```
- When executed next
    ```shell
    found syntax error when parsing DDL "CREATE TABLE "public"."users" (
        "id" bigserial NOT NULL,
        "name" text NOT NULL,
        "hoge_time" time NOT NULL DEFAULT '23:59:59'::time without time zone,
        PRIMARY KEY ("id")
    )": syntax error at position 150 near 'without'
    ```

## Expected output

No errors.

**Comment by k0kubun** [comment]
Thank you for your report. It appears that sqldef can parse your input, but it doesn't handle the data type output generated by the database.

psqldef uses PostgreSQL's original parser and converts its output to sqldef's own tree. So we don't need to write a parser; we need tree-to-tree conversion. It's implemented in `database/postgres/parser.go`, and its `parseTypeName()` probably lacks something for it. Would you be interested in working on a PR to fix it?

**Comment by shiroemons** [comment]
I would like to work on PR to solve the problem.

I investigated and found that I needed to add "time" at this location, but the syntax error remained the same.
https://github.com/k0kubun/sqldef/blob/79d3771fae7bc969664c6d01acf271f859bdad45/database/postgres/parser.go#L526

I would appreciate any advice on what else I should be looking at.

**Comment by k0kubun** [comment]
Thank you for having a look at it :+1:

Because psqldef uses multi-level parsers, it only shows the last-level, generic parser's errors by default. However, when you're developing the first-level parser, `database/postgres/parser.go`, you'd like to see errors coming from it.

You can modify the code around https://github.com/k0kubun/sqldef/blob/79d3771fae7bc969664c6d01acf271f859bdad45/database/postgres/parser.go#L45-L46 to print what that `err` is, which is not printed by the current code (off topic: maybe it's time to start printing both when both parsers fail). You probably resolved `unhandled type in parseTypeName` in `parseTypeName`, but there might be other issues we haven't fixed yet. What does the `err` say?

**Comment by shiroemons** [comment]
I ran it so that it outputs an error.
```go
		stmt, err := p.parseStmt(rawStmt.Stmt)
		if err != nil {
			fmt.Println(err)
```


- When first executed
```
unhandled contype: 7
-- Apply --
create table users (
  id        bigserial not null primary key,
  name      text      not null,
  hoge_time time      not null default '23:59:59'::time
);
```

- When executed next
```
unhandled contype: 7
unhandled type in parseTypeName: time
found syntax error when parsing DDL "CREATE TABLE "public"."users" (
    "id" bigserial NOT NULL,
    "name" text NOT NULL,
    "hoge_time" time NOT NULL DEFAULT '23:59:59'::time without time zone,
    PRIMARY KEY ("id")
)": syntax error at position 150 near 'without'
exit status 1
```

- Executed after fix parseTypeName
```
unhandled contype: 7
unhandled contype: 3
found syntax error when parsing DDL "CREATE TABLE "public"."users" (
    "id" bigserial NOT NULL,
    "name" text NOT NULL,
    "hoge_time" time NOT NULL DEFAULT '23:59:59'::time without time zone,
    PRIMARY KEY ("id")
)": syntax error at position 150 near 'without'
exit status 1
```

I am wondering if I need to add a process for the case of `pgquery.ConstrType_CONSTR_DEFAULT`.
However, we do not know what kind of process to write.

https://github.com/k0kubun/sqldef/blob/79d3771fae7bc969664c6d01acf271f859bdad45/database/postgres/parser.go#L488-L493

**Comment by k0kubun** [comment]
To investigate what kind of tree sqldef expects, I try to create a query that is close to the thing you want to parse and is still parseable by the second-level fallback parser (`parser/parser.go`). For `pgquery.ConstrType_CONSTR_DEFAULT`, assuming it's about `DEFAULT` and the fallback parser can parse `DEFAULT` in general, I would write a query that uses `DEFAULT` but no other features that it cannot parse yet, let the fallback parser parse it, and see the structure of the tree by printing it with https://github.com/k0kubun/pp.

After that, you can start with hard-coding the output for `pgquery.ConstrType_CONSTR_DEFAULT:`, and gradually replace its internals with references to the node given by PostgreSQL's original parser. For looking at the node given by PostgreSQL's original parser, again, https://github.com/k0kubun/pp is useful.

**Comment by shiroemons** [comment]
Since this issue does not occur in version v0.17.5, I am closing this issue.
