### ISSUE TITLE
[Feature] Support datasource Apache Doris

### ISSUE THREAD

**Issue by mklzl** [sqldef/sqldef#422]
Now , when we use mysql-def connect to Apache Doris ,it  will be some  syntax errors

## Significance

Apache Doris is an easy-to-use, high performance and unified analytics database,  it is a very meaningful thing for support this database

**Comment by k0kubun** [comment]
Is Apache Doris compatible with any of the already-supported drivers?

If not, we usually start developing new driver support in a fork under sqldef org. I can prepare a repository and invite a maintainer to it. I don't have experience in Apache Doris, so I need you to find somebody who can develop the first version and maintain it. Do you have any idea?

**Comment by k0kubun** [comment]
Closing until further information is provided. Thanks.
