### ISSUE TITLE
sqlite3def: can't I use foreign key constraints?

### ISSUE THREAD

**Issue by zztkm** [sqldef/sqldef#439]
## Platform

* OS: Linux
* RDBMS: SQLite3
* Version: unknown (probably the latest
On a separate note, `sqlite3def --version` does not output anything

## --export output

```shell
-- No table exists --
```

## Input SQL

```sql
CREATE TABLE artist(
  artistid    INTEGER PRIMARY KEY,
  artistname  TEXT
);
CREATE TABLE track(
  trackid     INTEGER,
  trackname   TEXT,
  trackartist INTEGER,
  FOREIGN KEY(trackartist) REFERENCES artist(artistid)
);
```

refs: https://www.sqlite.org/foreignkeys.html

## Current output

```shell
> sqlite3def -f schema.sql --dry-run db.sqlite
found syntax error when parsing DDL "CREATE TABLE track(
  trackid     INTEGER,
  trackname   TEXT,
  trackartist INTEGER,
  FOREIGN KEY(trackartist) REFERENCES artist(artistid)
)": syntax error at position 96 near 'foreign'
make: *** [Makefile:3: migration] Error 1
```

## Expected output

```shell
-- dry run --
CREATE TABLE artist(
  artistid    INTEGER PRIMARY KEY,
  artistname  TEXT
);
CREATE TABLE track(
  trackid     INTEGER,
  trackname   TEXT,
  trackartist INTEGER,
  FOREIGN KEY(trackartist) REFERENCES artist(artistid)
);
```

If there are any mistakes, it would be appreciated if you could let me know.

**Comment by k0kubun** [comment]
I think that's not a mistake on your end. It appears that sqldef's parser doesn't support parsing the syntax yet.

@knaka Is there any alternative syntax you use on sqlite3def?

**Comment by knaka** [comment]
In SQLite3, foreign key constraints are not a standard feature, which is why I haven't been using them. I haven't run into any issues without them. When I can find the time, I'm considering giving the implementation a try. @zztkm otherwise your PR is welcome.

**Comment by dirslashls** [comment]
Seems like an issue for PRIMARY KEY constraint as well.

**Comment by knaka** [comment]
The format for writing constraints on independent lines is unique to SQLite3, so the above DDL results in an error because thee generic parser does not accept it. The current version of sqlite3def accepts the following way of writing constraints along with column definitions.

```
CREATE TABLE artist(
  artistid    INTEGER PRIMARY KEY,
  artistname  TEXT
);
CREATE TABLE track(
  trackid     INTEGER,
  trackname   TEXT,
  trackartist INTEGER REFERENCES artist(artistid)
);
```

However, I will fix to accept DDLs written in SQLite3 documentation.

**Comment by zztkm** [comment]
@knaka thank you very much!
