### ISSUE TITLE
Ability to provide existing db connection to create database.Database

### ISSUE THREAD

**Issue by dirslashls** [sqldef/sqldef#465]
Hello, in my app, I already have connection to the database (*sql.DB object) and these connections make use of a lot of other config options not supported with sqldef. So, rather than creating a separate connection using the <db>.NewDatabase APIs, I am wondering if it is possible to make use of existing connections. Perhaps an API like

NewDatabaseWithConnection(config,db)

would create the dabatase.Database interfaces using the passed *sql.DB connection.

**Comment by k0kubun** [comment]
For maintainability reasons, we don't guarantee any API backward compatibility. For the same reason, we don't take feature requests in API. The CLI of the binary is the only official API that is intended to be maintained.

We still don't prevent users from using the Go API though. If making such changes improves sqldef's maintainability, we might merge it, and you might be able to use it until it's changed for other reasons. Feel free to open a PR if you think it's useful for maintaining sqldef.
