### ISSUE TITLE
Does command line support mysql text comparison?

### ISSUE THREAD

**Issue by zhengshuoo** [sqldef/sqldef#484]
Does the command line support MySQL text comparison like [sqldef.github.io](https://sqldef.github.io/)

Example SQL
```
mysqldef -d current_schema new_schema 
```
If it not supported， I can submit a PR to support it.

**Comment by k0kubun** [comment]
You can file two files. Try passing "--file sql" twice.

**Comment by zhengshuoo** [comment]
> You can diff two files. Try passing "--file [schema file]" twice.

That's not what I meant，passing "--file [schema file]" twice only desiredFiles

I mean, do not connect to the database, diff two files or two texts , One as source and one as target

**Comment by k0kubun** [comment]
If you don't believe what I'm saying, you may read the code https://github.com/sqldef/sqldef/pull/179 to confirm `--file [source] --file [desired]` doesn't indeed connect to the database.

**Comment by zhengshuoo** [comment]
Thanks for your suggestion.

I have read the code and confirmed the 0.11.17 version supports comparing --file options. 
But the latest version 0.16.15 not support it, need to specify a database, and when I specify a database, need to connect to the database.

### mysqldef-0.16.15
```
➜  mysqldef-0.16.15 --file /tmp/mysqldef/before.sql  --file /tmp/mysqldef/after.sql
No database is specified!

Usage:
  mysqldef-0.16.15 [options] db_name

➜ mysqldef-0.16.15 --file /tmp/mysqldef/before.sql  --file /tmp/mysqldef/after.sql dbName
2024/01/16 14:51:57 Error on DumpDDLs: Error 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
```

### mysqldef-0.11.17
```
➜ mysqldef-0.11.17 --file /tmp/mysqldef/before.sql  --file /tmp/mysqldef/after.sql
-- dry run --
ALTER TABLE `users` ADD COLUMN `name` varchar(40) DEFAULT null AFTER `id`;
```

**Comment by k0kubun** [comment]
Ugh, I'm sorry. Would you mind finding the first version that got broken?

**Comment by zhengshuoo** [comment]
I'll try

**Comment by zhengshuoo** [comment]
v0.15.0 2d441fd9
  - Comparing two `--file` options introduced in v0.11.17 is removed.
    Instead, you can specify an SQL file in the place of the database name.
    e.g. `mysqldef current.sql < desired.sql`

I will use the new way. Confusingly, the new way is not stated in the usage.

**Comment by k0kubun** [comment]
:man_facepalming: Why did I forget this myself?

If you have a suggested improvement in the help message, a pull request would be appreciated.

**Comment by zhengshuoo** [comment]
I'll improve the help message and submit a pull request soon.
