### ISSUE TITLE
[mysqldef] Cannot use mysql keyword as column name

### ISSUE THREAD

**Issue by yshrsmz** [sqldef/sqldef#496]
## Platform

* OS: Linux | macOS
* RDBMS: MySQL
* Version: 0.17.0

## --export output

```
CREATE TABLE users (
  user int UNSIGNED NOT NULL AUTO_INCREMENT,
  status varchar(32) NOT NULL,
  PRIMARY KEY (user_id)
)
```

## Input SQL
```
CREATE TABLE users (
  user int UNSIGNED NOT NULL AUTO_INCREMENT,
  status varchar(32) NOT NULL,
  PRIMARY KEY (user_id)
)
```

## Current output

`mysqldef test.sql --dry-run < test.sql` throws error below

```
found syntax error when parsing DDL "CREATE TABLE users (
  user int UNSIGNED NOT NULL AUTO_INCREMENT,
  status varchar(32) NOT NULL,
  PRIMARY KEY (user_id)
)": syntax error at position 75 near 'status'
```

## Expected output

```
-- Nothing is modified --
```

---

If I wrap `status` with backtick, it works fine

```
CREATE TABLE users (
  user int UNSIGNED NOT NULL AUTO_INCREMENT,
  `status` varchar(32) NOT NULL,
  PRIMARY KEY (user_id)
)
```

I also tested with `action` and got the same result.

https://dev.mysql.com/doc/refman/8.0/en/keywords.html

It looks like MySQL keywords are handled the same as reserved words. We should be able to use keywords as column names without error.

**Comment by k0kubun** [comment]
Yeah, it's unfortunately an intended change as of v0.17.0 https://github.com/sqldef/sqldef/blob/master/CHANGELOG.md#v0170, but it's supposed to be fixed again in future versions.

**Comment by k0kubun** [comment]
v0.17 doesn't have anything new for mysqldef, so you could keep using v0.16 until something is added for mysqldef.

**Comment by yshrsmz** [comment]
Ahh, right, the changelog clearly states this. That somehow slipped my eyes, thanks.
I think I'm going to stay using v0.16 for now.
