### ISSUE TITLE
[mysqldef] Suggestion: Add Config to specify ALGORITHM in alter statement

### ISSUE THREAD

**Issue by okaponta** [sqldef/sqldef#518]
We want to specify ALGORITHM option in ALTER statements.
ex) `ALTER TABLE tbl_name RENAME INDEX old_index_name TO new_index_name, ALGORITHM=INPLACE, LOCK=NONE;`

Do you think it's a good idea to introduce an option for specifying the ALGORITHM statement?
If so, I'd like to proceed with implementing the configuration.

**Comment by k0kubun** [comment]
Sure, I'm open to adding that feature. Since the feature is not part of the `mysql` command, I would like it to be added to a config given to `--config` (We try to minimize the difference between `mysql` command-line options and `mysqldef` options).

**Comment by okaponta** [comment]
Thank you, I will try to add ALGORITHM option to `--config`!

**Comment by okaponta** [comment]
@k0kubun 
I tried to implement it, but I haven't had much experience with Golang, and I'm not sure how to make the tests pass... 🙇 
Could you please help me? 

https://github.com/sqldef/sqldef/pull/519

**Comment by k0kubun** [comment]
It appears that you only implemented the configuration. `schema/generator.go` is the file you need to modify to change generated DDLs. Can you also change that file to implement the logic?

**Comment by okaponta** [comment]
Thank you, I moved the logic to generator.
Actually, the problem was my code.

before (the element in ddls don't change)
```go
for i, ddl := range ddls {
	if strings.HasPrefix(ddl, "ALTER TABLE") {
		ddl += ", ALGORITHM=" + strings.ToUpper(g.algorithm)
	}
}
```

after
```go
for i := range ddls {
	if strings.HasPrefix(ddls[i], "ALTER TABLE") {
		ddls[i] += ", ALGORITHM=" + strings.ToUpper(g.algorithm)
	}
}
```

I managed the test to pass, so I'll check my code and make PR this weekend!!

**Comment by k0kubun** [comment]
merged https://github.com/sqldef/sqldef/pull/519
