### ISSUE TITLE
sqlite3def: "IF NOT EXISTS" isn't needed for "CREATE INDEX" ?

### ISSUE THREAD

**Issue by morishin** [sqldef/sqldef#534]
## Platform

* OS: macOS
* RDBMS: SQLite3
* Version:

## --export output

```sh
$ sqlite3def --export current.sql < current.sql
```

```sql
CREATE TABLE IF NOT EXISTS "User" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL
);

CREATE UNIQUE INDEX "User_name_key" ON "User"("name");
```

## Input SQL

current.sql
```sql
CREATE TABLE "User" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL
);
CREATE UNIQUE INDEX "User_name_key" ON "User"("name");
```

## Current output

```sql
...
CREATE UNIQUE INDEX "User_name_key" ON "User"("name");
```

## Expected output

```sql
...
CREATE UNIQUE INDEX IF NOT EXISTS "User_name_key" ON "User"("name");
```

**Comment by hokaccha** [comment]
sqldef detects the difference and does not issue create index if index exists so I think "IF NOT EXISTS" is unnecessary.  If you have a use case that needs to be made, can you give us a more detailed use case?

**Comment by morishin** [comment]
I was mistaken 🙇‍♂️
I thought `--export` outputs the SQL to be applied, but it actually dumps the current schema.
